// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CallbackData, CallbackErrors, DeleteConsoleAuthData, DeleteConsoleAuthErrors, DeleteConsoleAuthResponses, DeleteLarkAppData, DeleteLarkAppErrors, DeleteLarkAppResponses, DispatchActionData, DispatchActionErrors, DispatchActionResponses, GetConfigData, GetConfigResponses, GetConsoleAuthData, GetConsoleAuthResponses, GetStatusData, GetStatusResponses, HealthData, HealthResponses, ListAppsData, ListAppsResponses, ListLarkAppsData, ListLarkAppsResponses, LoginData, LoginErrors, LogoutData, LogoutResponses, MeData, MeResponses, PutConfigData, PutConfigErrors, PutConfigResponses, PutConsoleAuthData, PutConsoleAuthErrors, PutConsoleAuthResponses, SetAppEnabledData, SetAppEnabledErrors, SetAppEnabledResponses, SetAppLarkAppData, SetAppLarkAppErrors, SetAppLarkAppResponses, StreamEventsData, StreamEventsResponse, StreamEventsResponses, TestLarkAppData, TestLarkAppResponses, UpsertLarkAppData, UpsertLarkAppErrors, UpsertLarkAppResponses } from './types.gen';
import { zDeleteConsoleAuthResponse, zDeleteLarkAppResponse, zDispatchActionResponse, zGetConfigResponse, zGetConsoleAuthResponse, zGetStatusResponse, zHealthResponse, zListAppsResponse, zListLarkAppsResponse, zLogoutResponse, zMeResponse, zPutConfigResponse, zPutConsoleAuthResponse, zSetAppEnabledResponse, zSetAppLarkAppResponse, zStreamEventsResponse, zTestLarkAppResponse, zUpsertLarkAppResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * `POST /api/actions/{app}/{action}` — fire-and-forget an App action. The
 * result string from `Instance::handle_action` surfaces on the event stream,
 * not in this response.
 */
export const dispatchAction = <ThrowOnError extends boolean = true>(options: Options<DispatchActionData, ThrowOnError>): RequestResult<DispatchActionResponses, DispatchActionErrors, ThrowOnError> => (options.client ?? client).post<DispatchActionResponses, DispatchActionErrors, ThrowOnError>({
    responseValidator: async (data) => await zDispatchActionResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/actions/{app}/{action}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `GET /api/apps` — registered App manifests, for generic UI rendering.
 */
export const listApps = <ThrowOnError extends boolean = true>(options?: Options<ListAppsData, ThrowOnError>): RequestResult<ListAppsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAppsResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zListAppsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/apps',
    ...options
});

/**
 * `GET /api/config` — the current `config.toml`, verbatim.
 */
export const getConfig = <ThrowOnError extends boolean = true>(options?: Options<GetConfigData, ThrowOnError>): RequestResult<GetConfigResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetConfigResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zGetConfigResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/config',
    ...options
});

/**
 * `PUT /api/config` — validate, persist, and broadcast a replacement config.
 * Only the apps whose change key moved are restarted.
 */
export const putConfig = <ThrowOnError extends boolean = true>(options: Options<PutConfigData, ThrowOnError>): RequestResult<PutConfigResponses, PutConfigErrors, ThrowOnError> => (options.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
    responseValidator: async (data) => await zPutConfigResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/config',
    ...options,
    headers: {
        'Content-Type': 'application/toml',
        ...options.headers
    }
});

/**
 * `PUT /api/config/{app}/enabled` — flip whether the supervisor runs an app,
 * writing just `[<app>].enabled` and leaving the rest of the config (comments
 * and all) untouched. A one-field affordance over the raw TOML editor for the
 * most common config edit; the affected app (re)starts or stops on broadcast.
 */
export const setAppEnabled = <ThrowOnError extends boolean = true>(options: Options<SetAppEnabledData, ThrowOnError>): RequestResult<SetAppEnabledResponses, SetAppEnabledErrors, ThrowOnError> => (options.client ?? client).put<SetAppEnabledResponses, SetAppEnabledErrors, ThrowOnError>({
    responseValidator: async (data) => await zSetAppEnabledResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/config/{app}/enabled',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `PUT /api/config/{app}/lark-app` — bind (or clear) the `[lark-apps.<name>]`
 * an app uses for Lark credentials, writing just `[<app>].lark_app` and leaving
 * the rest of the config untouched. A one-field affordance over the raw TOML
 * editor; the affected app restarts on broadcast and resolves the new binding.
 * A non-empty value must name a registered Lark app, else the app would fail
 * its next build — so we reject it up front.
 */
export const setAppLarkApp = <ThrowOnError extends boolean = true>(options: Options<SetAppLarkAppData, ThrowOnError>): RequestResult<SetAppLarkAppResponses, SetAppLarkAppErrors, ThrowOnError> => (options.client ?? client).put<SetAppLarkAppResponses, SetAppLarkAppErrors, ThrowOnError>({
    responseValidator: async (data) => await zSetAppLarkAppResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/config/{app}/lark-app',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `DELETE /api/console-auth` — unbind, reopening the console. The recovery path
 * when an operator is about to lock themselves out (admins list omits them).
 */
export const deleteConsoleAuth = <ThrowOnError extends boolean = true>(options?: Options<DeleteConsoleAuthData, ThrowOnError>): RequestResult<DeleteConsoleAuthResponses, DeleteConsoleAuthErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteConsoleAuthResponses, DeleteConsoleAuthErrors, ThrowOnError>({
    responseValidator: async (data) => await zDeleteConsoleAuthResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/console-auth',
    ...options
});

/**
 * `GET /api/console-auth` — the current console sign-in binding.
 */
export const getConsoleAuth = <ThrowOnError extends boolean = true>(options?: Options<GetConsoleAuthData, ThrowOnError>): RequestResult<GetConsoleAuthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetConsoleAuthResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zGetConsoleAuthResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/console-auth',
    ...options
});

/**
 * `PUT /api/console-auth` — bind a Lark app as the console's OAuth client.
 * Saving this enforces sign-in on the next request, so the bound app must
 * already carry working credentials in the registry (else the console would
 * silently stay open).
 */
export const putConsoleAuth = <ThrowOnError extends boolean = true>(options: Options<PutConsoleAuthData, ThrowOnError>): RequestResult<PutConsoleAuthResponses, PutConsoleAuthErrors, ThrowOnError> => (options.client ?? client).put<PutConsoleAuthResponses, PutConsoleAuthErrors, ThrowOnError>({
    responseValidator: async (data) => await zPutConsoleAuthResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/console-auth',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `GET /api/events` — backfill recent events, then stream live ones. Honors
 * `?since=<id>` and the `Last-Event-ID` header for reconnect backfill.
 *
 * Each message's `data` is a JSON `Event`
 * `{ id, level, subsystem, target, message, fields, timestamp }`. A `lagged`
 * event signals the client fell behind and some events were dropped.
 */
export const streamEvents = <ThrowOnError extends boolean = true>(options?: Options<StreamEventsData, ThrowOnError, StreamEventsResponse>): Promise<ServerSentEventsResult<StreamEventsResponses>> => (options?.client ?? client).sse.get<StreamEventsResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zStreamEventsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/events',
    ...options
});

/**
 * `GET /api/health` — ungated liveness probe.
 */
export const health = <ThrowOnError extends boolean = true>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zHealthResponse.parseAsync(data),
    url: '/api/health',
    ...options
});

/**
 * `GET /api/lark-apps` — the registry, `app_secret` redacted to a boolean.
 */
export const listLarkApps = <ThrowOnError extends boolean = true>(options?: Options<ListLarkAppsData, ThrowOnError>): RequestResult<ListLarkAppsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListLarkAppsResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zListLarkAppsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/lark-apps',
    ...options
});

/**
 * `POST /api/lark-apps` — live-test the credentials, then write the entry.
 * Nothing is persisted unless the test passes.
 */
export const upsertLarkApp = <ThrowOnError extends boolean = true>(options: Options<UpsertLarkAppData, ThrowOnError>): RequestResult<UpsertLarkAppResponses, UpsertLarkAppErrors, ThrowOnError> => (options.client ?? client).post<UpsertLarkAppResponses, UpsertLarkAppErrors, ThrowOnError>({
    responseValidator: async (data) => await zUpsertLarkAppResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/lark-apps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `POST /api/lark-apps/test` — dry-run a credential check without saving.
 * Always `200`; the body's `ok` flag carries the verdict.
 */
export const testLarkApp = <ThrowOnError extends boolean = true>(options: Options<TestLarkAppData, ThrowOnError>): RequestResult<TestLarkAppResponses, unknown, ThrowOnError> => (options.client ?? client).post<TestLarkAppResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zTestLarkAppResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/lark-apps/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * `DELETE /api/lark-apps/{name}` — drop an entry. Apps still referencing it
 * will fail their next build (surfaced as Errored in the console).
 */
export const deleteLarkApp = <ThrowOnError extends boolean = true>(options: Options<DeleteLarkAppData, ThrowOnError>): RequestResult<DeleteLarkAppResponses, DeleteLarkAppErrors, ThrowOnError> => (options.client ?? client).delete<DeleteLarkAppResponses, DeleteLarkAppErrors, ThrowOnError>({
    responseValidator: async (data) => await zDeleteLarkAppResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/lark-apps/{name}',
    ...options
});

/**
 * `GET /api/status` — latest liveness of every supervised subsystem.
 */
export const getStatus = <ThrowOnError extends boolean = true>(options?: Options<GetStatusData, ThrowOnError>): RequestResult<GetStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zGetStatusResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'lk_session',
            type: 'apiKey'
        }],
    url: '/api/status',
    ...options
});

/**
 * `GET /auth/callback` — exchange the code, check the allowlist, mint a
 * session.
 */
export const callback = <ThrowOnError extends boolean = true>(options?: Options<CallbackData, ThrowOnError>): RequestResult<unknown, CallbackErrors, ThrowOnError> => (options?.client ?? client).get<unknown, CallbackErrors, ThrowOnError>({ url: '/auth/callback', ...options });

/**
 * `GET /auth/login` — start the OAuth handshake; redirect to Lark.
 */
export const login = <ThrowOnError extends boolean = true>(options?: Options<LoginData, ThrowOnError>): RequestResult<unknown, LoginErrors, ThrowOnError> => (options?.client ?? client).get<unknown, LoginErrors, ThrowOnError>({ url: '/auth/login', ...options });

/**
 * `POST /auth/logout` — drop the session cookie.
 */
export const logout = <ThrowOnError extends boolean = true>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zLogoutResponse.parseAsync(data),
    url: '/auth/logout',
    ...options
});

/**
 * `GET /auth/me` — ungated; tells the UI whether to show the login screen.
 */
export const me = <ThrowOnError extends boolean = true>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zMeResponse.parseAsync(data),
    url: '/auth/me',
    ...options
});
