// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Acknowledgement that an action was queued for the running App.
 */
export type ActionAck = {
    action: string;
    app: string;
    ok: boolean;
};

/**
 * Wire mirror of `larkstack_core::ActionSpec`.
 */
export type AppActionSpec = {
    description: string;
    name: string;
    /**
     * Free-form JSON descriptor the UI renders a form from; omitted when the
     * action takes no parameters.
     */
    params?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Wire mirror of `larkstack_core::Kind`.
 */
export const AppKind = { INTEGRATION: 'integration', AUTOMATION: 'automation' } as const;

/**
 * Wire mirror of `larkstack_core::Kind`.
 */
export type AppKind = typeof AppKind[keyof typeof AppKind];

/**
 * Wire mirror of `larkstack_core::Manifest`, plus the live `enabled` flag read
 * from config (the manifest itself is static; `enabled` is operator state).
 */
export type AppManifest = {
    actions: Array<AppActionSpec>;
    description: string;
    /**
     * Whether the supervisor is configured to run this app (`[<name>].enabled`).
     */
    enabled: boolean;
    kind: AppKind;
    /**
     * The `[lark-apps.<name>]` this app binds for Lark credentials
     * (`[<name>].lark_app`), if any. Editable via `PUT /api/config/{app}/lark-app`.
     */
    lark_app?: string | null;
    name: string;
};

/**
 * Body of `GET /api/apps`.
 */
export type AppsResponse = {
    apps: Array<AppManifest>;
};

export type BindReq = {
    /**
     * Admin email allowlist; empty = any tenant user may sign in.
     */
    admins?: Array<string>;
    /**
     * Name of a registered `[lark-apps.<name>]` to sign users in with.
     */
    lark_app: string;
    /**
     * Override the auto-derived `<host>/auth/callback` (must match what the
     * Lark app registers).
     */
    redirect_uri?: string | null;
    /**
     * Extra OAuth scopes, space-separated (usually none).
     */
    scope?: string | null;
};

/**
 * Body of `GET /api/console-auth`.
 */
export type ConsoleAuthView = {
    /**
     * Admin email allowlist (empty = any tenant user may sign in).
     */
    admins: Array<string>;
    /**
     * Whether sign-in is currently enforced (a Lark app with working
     * credentials is bound). When false the console is OPEN.
     */
    configured: boolean;
    /**
     * The bound `[lark-apps.<name>]`, if any.
     */
    lark_app?: string | null;
    redirect_uri?: string | null;
    scope?: string | null;
};

export type EnabledAck = {
    enabled: boolean;
    name: string;
    ok: boolean;
};

export type EnabledReq = {
    enabled: boolean;
};

/**
 * Error body shared by every non-2xx JSON response.
 */
export type ErrorResponse = {
    error: string;
};

/**
 * Wire shape of one SSE `data` payload — mirrors [`larkstack_core::Event`]'s
 * serde output, declared here so the schema lands in the OpenAPI spec without
 * `larkstack-core` depending on `utoipa`. Never constructed: the handler
 * serializes the core event directly.
 */
export type Event = {
    fields: {
        [key: string]: unknown;
    };
    id: number;
    level: Level;
    message: string;
    subsystem?: string | null;
    target: string;
    /**
     * Unix milliseconds.
     */
    timestamp: number;
};

export type LarkAppAck = {
    lark_app?: string | null;
    name: string;
    ok: boolean;
};

export type LarkAppReq = {
    /**
     * The `[lark-apps.<name>]` to bind for this app's Lark credentials, or
     * `null`/empty to unbind (falling back to env / inline `[<app>.lark]`).
     */
    lark_app?: string | null;
};

/**
 * One registry entry, with the secret redacted to a flag.
 */
export type LarkAppView = {
    app_id: string;
    base_url: string;
    /**
     * Whether an `app_secret` is stored (the secret itself is never returned).
     */
    has_secret: boolean;
    name: string;
};

/**
 * Body of `GET /api/lark-apps`.
 */
export type LarkAppsResponse = {
    lark_apps: Array<LarkAppView>;
};

/**
 * Mirrors [`larkstack_core::Level`]'s lowercase serde encoding.
 */
export const Level = {
    TRACE: 'trace',
    DEBUG: 'debug',
    INFO: 'info',
    WARN: 'warn',
    ERROR: 'error'
} as const;

/**
 * Mirrors [`larkstack_core::Level`]'s lowercase serde encoding.
 */
export type Level = typeof Level[keyof typeof Level];

export type Me = {
    /**
     * Whether OAuth is configured at all. When false the console is open.
     */
    auth_required: boolean;
    authenticated: boolean;
    user?: null | MeUser;
};

export type MeUser = {
    email: string;
    name: string;
};

/**
 * Generic `{ "ok": true }` success body.
 */
export type OkResponse = {
    ok: boolean;
};

/**
 * Body of `GET /api/status`.
 */
export type StatusResponse = {
    /**
     * Subsystem name → its latest status.
     */
    subsystems: {
        [key: string]: SubsystemStatus;
    };
};

/**
 * Wire mirror of `larkstack_core::State`.
 */
export const SubsystemState = {
    STARTING: 'starting',
    RUNNING: 'running',
    ERRORED: 'errored',
    STOPPED: 'stopped'
} as const;

/**
 * Wire mirror of `larkstack_core::State`.
 */
export type SubsystemState = typeof SubsystemState[keyof typeof SubsystemState];

/**
 * One subsystem's status — wire mirror of `larkstack_core::Status`.
 */
export type SubsystemStatus = {
    message?: string | null;
    state: SubsystemState;
    /**
     * Unix-epoch milliseconds of the last transition.
     */
    updated_at: number;
};

export type TestReq = {
    app_id: string;
    app_secret: string;
    base_url?: string | null;
};

/**
 * Body of `POST /api/lark-apps/test`: `ok` plus either the token lifetime or
 * the failure reason.
 */
export type TestResult = {
    /**
     * Failure reason, on error.
     */
    error?: string | null;
    /**
     * Token lifetime in seconds, on success.
     */
    expire?: number | null;
    ok: boolean;
};

/**
 * Body of a successful `POST /api/lark-apps`.
 */
export type UpsertAck = {
    name: string;
    ok: boolean;
};

export type UpsertReq = {
    app_id: string;
    app_secret: string;
    base_url?: string | null;
    name: string;
};

export type DispatchActionData = {
    /**
     * Optional action parameters (JSON object)
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Registered app name
         */
        app: string;
        /**
         * Action name from the app's manifest
         */
        action: string;
    };
    query?: never;
    url: '/api/actions/{app}/{action}';
};

export type DispatchActionErrors = {
    /**
     * Unknown app
     */
    404: ErrorResponse;
    /**
     * App is not running
     */
    503: ErrorResponse;
};

export type DispatchActionError = DispatchActionErrors[keyof DispatchActionErrors];

export type DispatchActionResponses = {
    /**
     * Action dispatched
     */
    202: ActionAck;
};

export type DispatchActionResponse = DispatchActionResponses[keyof DispatchActionResponses];

export type ListAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps';
};

export type ListAppsResponses = {
    /**
     * Registered app manifests
     */
    200: AppsResponse;
};

export type ListAppsResponse = ListAppsResponses[keyof ListAppsResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigResponses = {
    /**
     * Current config.toml
     */
    200: string;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type PutConfigData = {
    /**
     * Full replacement config.toml
     */
    body: string;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type PutConfigErrors = {
    /**
     * Body is not valid TOML
     */
    400: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type PutConfigError = PutConfigErrors[keyof PutConfigErrors];

export type PutConfigResponses = {
    /**
     * Saved; affected apps restart
     */
    200: OkResponse;
};

export type PutConfigResponse = PutConfigResponses[keyof PutConfigResponses];

export type SetAppEnabledData = {
    body: EnabledReq;
    path: {
        /**
         * Registered app name
         */
        app: string;
    };
    query?: never;
    url: '/api/config/{app}/enabled';
};

export type SetAppEnabledErrors = {
    /**
     * That config section is not a table
     */
    400: ErrorResponse;
    /**
     * No such registered app
     */
    404: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type SetAppEnabledError = SetAppEnabledErrors[keyof SetAppEnabledErrors];

export type SetAppEnabledResponses = {
    /**
     * Flag set; the app starts or stops
     */
    200: EnabledAck;
};

export type SetAppEnabledResponse = SetAppEnabledResponses[keyof SetAppEnabledResponses];

export type SetAppLarkAppData = {
    body: LarkAppReq;
    path: {
        /**
         * Registered app name
         */
        app: string;
    };
    query?: never;
    url: '/api/config/{app}/lark-app';
};

export type SetAppLarkAppErrors = {
    /**
     * lark_app is not a registered Lark app, or the section is not a table
     */
    400: ErrorResponse;
    /**
     * No such registered app
     */
    404: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type SetAppLarkAppError = SetAppLarkAppErrors[keyof SetAppLarkAppErrors];

export type SetAppLarkAppResponses = {
    /**
     * Binding set (or cleared); the app restarts
     */
    200: LarkAppAck;
};

export type SetAppLarkAppResponse = SetAppLarkAppResponses[keyof SetAppLarkAppResponses];

export type DeleteConsoleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/console-auth';
};

export type DeleteConsoleAuthErrors = {
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type DeleteConsoleAuthError = DeleteConsoleAuthErrors[keyof DeleteConsoleAuthErrors];

export type DeleteConsoleAuthResponses = {
    /**
     * Unbound; the console is open again
     */
    200: OkResponse;
};

export type DeleteConsoleAuthResponse = DeleteConsoleAuthResponses[keyof DeleteConsoleAuthResponses];

export type GetConsoleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/console-auth';
};

export type GetConsoleAuthResponses = {
    /**
     * Console sign-in binding
     */
    200: ConsoleAuthView;
};

export type GetConsoleAuthResponse = GetConsoleAuthResponses[keyof GetConsoleAuthResponses];

export type PutConsoleAuthData = {
    body: BindReq;
    path?: never;
    query?: never;
    url: '/api/console-auth';
};

export type PutConsoleAuthErrors = {
    /**
     * lark_app is not a registered app with credentials
     */
    400: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type PutConsoleAuthError = PutConsoleAuthErrors[keyof PutConsoleAuthErrors];

export type PutConsoleAuthResponses = {
    /**
     * Binding saved; sign-in now required
     */
    200: OkResponse;
};

export type PutConsoleAuthResponse = PutConsoleAuthResponses[keyof PutConsoleAuthResponses];

export type StreamEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Replay events with id greater than this (same role as `Last-Event-ID`).
         */
        since?: number;
    };
    url: '/api/events';
};

export type StreamEventsResponses = {
    /**
     * SSE stream of console events; each message's `data` is one JSON `Event`
     */
    200: Event;
};

export type StreamEventsResponse = StreamEventsResponses[keyof StreamEventsResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Service is up
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ListLarkAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/lark-apps';
};

export type ListLarkAppsResponses = {
    /**
     * Registered Lark apps (secrets redacted)
     */
    200: LarkAppsResponse;
};

export type ListLarkAppsResponse = ListLarkAppsResponses[keyof ListLarkAppsResponses];

export type UpsertLarkAppData = {
    body: UpsertReq;
    path?: never;
    query?: never;
    url: '/api/lark-apps';
};

export type UpsertLarkAppErrors = {
    /**
     * Invalid input or failed credential test
     */
    400: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type UpsertLarkAppError = UpsertLarkAppErrors[keyof UpsertLarkAppErrors];

export type UpsertLarkAppResponses = {
    /**
     * Credentials valid and saved
     */
    200: UpsertAck;
};

export type UpsertLarkAppResponse = UpsertLarkAppResponses[keyof UpsertLarkAppResponses];

export type TestLarkAppData = {
    body: TestReq;
    path?: never;
    query?: never;
    url: '/api/lark-apps/test';
};

export type TestLarkAppResponses = {
    /**
     * Credential-test verdict
     */
    200: TestResult;
};

export type TestLarkAppResponse = TestLarkAppResponses[keyof TestLarkAppResponses];

export type DeleteLarkAppData = {
    body?: never;
    path: {
        /**
         * Registry entry name
         */
        name: string;
    };
    query?: never;
    url: '/api/lark-apps/{name}';
};

export type DeleteLarkAppErrors = {
    /**
     * No such entry
     */
    404: ErrorResponse;
    /**
     * Could not write the config file
     */
    500: ErrorResponse;
};

export type DeleteLarkAppError = DeleteLarkAppErrors[keyof DeleteLarkAppErrors];

export type DeleteLarkAppResponses = {
    /**
     * Entry removed
     */
    200: OkResponse;
};

export type DeleteLarkAppResponse = DeleteLarkAppResponses[keyof DeleteLarkAppResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type GetStatusResponses = {
    /**
     * Per-subsystem status snapshot
     */
    200: StatusResponse;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type CallbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Authorization code from Lark (present on success).
         */
        code?: string;
        /**
         * Opaque state echoed back; must match the login handshake.
         */
        state?: string;
        /**
         * Error code from Lark (present when the user denied access).
         */
        error?: string;
    };
    url: '/auth/callback';
};

export type CallbackErrors = {
    /**
     * Missing/mismatched login state, or a Lark error
     */
    400: unknown;
    /**
     * Account is not in [console].admins
     */
    403: unknown;
    /**
     * Token exchange or user_info request failed
     */
    502: unknown;
};

export type LoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * OAuth is not configured
     */
    400: unknown;
    /**
     * Could not build the authorize URL
     */
    500: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Session cleared
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeResponses = {
    /**
     * Auth + current session state
     */
    200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];
