// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts
// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Acknowledgement that an action was queued for the running App.
 */
export const zActionAck = z.object({
    action: z.string(),
    app: z.string(),
    ok: z.boolean()
}).register(z.globalRegistry, {
    description: 'Acknowledgement that an action was queued for the running App.'
});

/**
 * Wire mirror of `larkstack_core::ActionSpec`.
 */
export const zAppActionSpec = z.object({
    description: z.string(),
    name: z.string(),
    params: z.record(z.string(), z.unknown()).nullish()
}).register(z.globalRegistry, {
    description: 'Wire mirror of `larkstack_core::ActionSpec`.'
});

/**
 * Wire mirror of `larkstack_core::Kind`.
 */
export const zAppKind = z.enum(['integration', 'automation']).register(z.globalRegistry, {
    description: 'Wire mirror of `larkstack_core::Kind`.'
});

/**
 * Wire mirror of `larkstack_core::Manifest`, plus the live `enabled` flag read
 * from config (the manifest itself is static; `enabled` is operator state).
 */
export const zAppManifest = z.object({
    actions: z.array(zAppActionSpec),
    description: z.string(),
    enabled: z.boolean().register(z.globalRegistry, {
        description: 'Whether the supervisor is configured to run this app (`[<name>].enabled`).'
    }),
    kind: zAppKind,
    lark_app: z.string().nullish(),
    name: z.string()
}).register(z.globalRegistry, {
    description: 'Wire mirror of `larkstack_core::Manifest`, plus the live `enabled` flag read\nfrom config (the manifest itself is static; `enabled` is operator state).'
});

/**
 * Body of `GET /api/apps`.
 */
export const zAppsResponse = z.object({
    apps: z.array(zAppManifest)
}).register(z.globalRegistry, {
    description: 'Body of `GET /api/apps`.'
});

export const zBindReq = z.object({
    admins: z.array(z.string()).register(z.globalRegistry, {
        description: 'Admin email allowlist; empty = any tenant user may sign in.'
    }).optional(),
    lark_app: z.string().register(z.globalRegistry, {
        description: 'Name of a registered `[lark-apps.<name>]` to sign users in with.'
    }),
    redirect_uri: z.string().nullish(),
    scope: z.string().nullish()
});

/**
 * Body of `GET /api/console-auth`.
 */
export const zConsoleAuthView = z.object({
    admins: z.array(z.string()).register(z.globalRegistry, {
        description: 'Admin email allowlist (empty = any tenant user may sign in).'
    }),
    configured: z.boolean().register(z.globalRegistry, {
        description: 'Whether sign-in is currently enforced (a Lark app with working\ncredentials is bound). When false the console is OPEN.'
    }),
    lark_app: z.string().nullish(),
    redirect_uri: z.string().nullish(),
    scope: z.string().nullish()
}).register(z.globalRegistry, {
    description: 'Body of `GET /api/console-auth`.'
});

export const zEnabledAck = z.object({
    enabled: z.boolean(),
    name: z.string(),
    ok: z.boolean()
});

export const zEnabledReq = z.object({
    enabled: z.boolean()
});

/**
 * Error body shared by every non-2xx JSON response.
 */
export const zErrorResponse = z.object({
    error: z.string()
}).register(z.globalRegistry, {
    description: 'Error body shared by every non-2xx JSON response.'
});

export const zLarkAppAck = z.object({
    lark_app: z.string().nullish(),
    name: z.string(),
    ok: z.boolean()
});

export const zLarkAppReq = z.object({
    lark_app: z.string().nullish()
});

/**
 * One registry entry, with the secret redacted to a flag.
 */
export const zLarkAppView = z.object({
    app_id: z.string(),
    base_url: z.string(),
    has_secret: z.boolean().register(z.globalRegistry, {
        description: 'Whether an `app_secret` is stored (the secret itself is never returned).'
    }),
    name: z.string()
}).register(z.globalRegistry, {
    description: 'One registry entry, with the secret redacted to a flag.'
});

/**
 * Body of `GET /api/lark-apps`.
 */
export const zLarkAppsResponse = z.object({
    lark_apps: z.array(zLarkAppView)
}).register(z.globalRegistry, {
    description: 'Body of `GET /api/lark-apps`.'
});

/**
 * Mirrors [`larkstack_core::Level`]'s lowercase serde encoding.
 */
export const zLevel = z.enum([
    'trace',
    'debug',
    'info',
    'warn',
    'error'
]).register(z.globalRegistry, {
    description: 'Mirrors [`larkstack_core::Level`]\'s lowercase serde encoding.'
});

/**
 * Wire shape of one SSE `data` payload — mirrors [`larkstack_core::Event`]'s
 * serde output, declared here so the schema lands in the OpenAPI spec without
 * `larkstack-core` depending on `utoipa`. Never constructed: the handler
 * serializes the core event directly.
 */
export const zEvent = z.object({
    fields: z.record(z.string(), z.unknown()),
    id: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    level: zLevel,
    message: z.string(),
    subsystem: z.string().nullish(),
    target: z.string(),
    timestamp: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).register(z.globalRegistry, {
        description: 'Unix milliseconds.'
    })
}).register(z.globalRegistry, {
    description: 'Wire shape of one SSE `data` payload — mirrors [`larkstack_core::Event`]\'s\nserde output, declared here so the schema lands in the OpenAPI spec without\n`larkstack-core` depending on `utoipa`. Never constructed: the handler\nserializes the core event directly.'
});

export const zMeUser = z.object({
    email: z.string(),
    name: z.string()
});

export const zMe = z.object({
    auth_required: z.boolean().register(z.globalRegistry, {
        description: 'Whether OAuth is configured at all. When false the console is open.'
    }),
    authenticated: z.boolean(),
    user: zMeUser.nullish()
});

/**
 * Generic `{ "ok": true }` success body.
 */
export const zOkResponse = z.object({
    ok: z.boolean()
}).register(z.globalRegistry, {
    description: 'Generic `{ "ok": true }` success body.'
});

/**
 * Wire mirror of `larkstack_core::State`.
 */
export const zSubsystemState = z.enum([
    'starting',
    'running',
    'errored',
    'stopped'
]).register(z.globalRegistry, {
    description: 'Wire mirror of `larkstack_core::State`.'
});

/**
 * One subsystem's status — wire mirror of `larkstack_core::Status`.
 */
export const zSubsystemStatus = z.object({
    message: z.string().nullish(),
    state: zSubsystemState,
    updated_at: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).register(z.globalRegistry, {
        description: 'Unix-epoch milliseconds of the last transition.'
    })
}).register(z.globalRegistry, {
    description: 'One subsystem\'s status — wire mirror of `larkstack_core::Status`.'
});

/**
 * Body of `GET /api/status`.
 */
export const zStatusResponse = z.object({
    subsystems: z.record(z.string(), zSubsystemStatus).register(z.globalRegistry, {
        description: 'Subsystem name → its latest status.'
    })
}).register(z.globalRegistry, {
    description: 'Body of `GET /api/status`.'
});

export const zTestReq = z.object({
    app_id: z.string(),
    app_secret: z.string(),
    base_url: z.string().nullish()
});

/**
 * Body of `POST /api/lark-apps/test`: `ok` plus either the token lifetime or
 * the failure reason.
 */
export const zTestResult = z.object({
    error: z.string().nullish(),
    expire: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullish(),
    ok: z.boolean()
}).register(z.globalRegistry, {
    description: 'Body of `POST /api/lark-apps/test`: `ok` plus either the token lifetime or\nthe failure reason.'
});

/**
 * Body of a successful `POST /api/lark-apps`.
 */
export const zUpsertAck = z.object({
    name: z.string(),
    ok: z.boolean()
}).register(z.globalRegistry, {
    description: 'Body of a successful `POST /api/lark-apps`.'
});

export const zUpsertReq = z.object({
    app_id: z.string(),
    app_secret: z.string(),
    base_url: z.string().nullish(),
    name: z.string()
});

/**
 * Optional action parameters (JSON object)
 */
export const zDispatchActionBody = z.record(z.string(), z.unknown()).register(z.globalRegistry, {
    description: 'Optional action parameters (JSON object)'
});

export const zDispatchActionPath = z.object({
    app: z.string().register(z.globalRegistry, {
        description: 'Registered app name'
    }),
    action: z.string().register(z.globalRegistry, {
        description: 'Action name from the app\'s manifest'
    })
});

/**
 * Action dispatched
 */
export const zDispatchActionResponse = zActionAck;

/**
 * Registered app manifests
 */
export const zListAppsResponse = zAppsResponse;

/**
 * Current config.toml
 */
export const zGetConfigResponse = z.string().register(z.globalRegistry, {
    description: 'Current config.toml'
});

/**
 * Full replacement config.toml
 */
export const zPutConfigBody = z.string().register(z.globalRegistry, {
    description: 'Full replacement config.toml'
});

/**
 * Saved; affected apps restart
 */
export const zPutConfigResponse = zOkResponse;

export const zSetAppEnabledBody = zEnabledReq;

export const zSetAppEnabledPath = z.object({
    app: z.string().register(z.globalRegistry, {
        description: 'Registered app name'
    })
});

/**
 * Flag set; the app starts or stops
 */
export const zSetAppEnabledResponse = zEnabledAck;

export const zSetAppLarkAppBody = zLarkAppReq;

export const zSetAppLarkAppPath = z.object({
    app: z.string().register(z.globalRegistry, {
        description: 'Registered app name'
    })
});

/**
 * Binding set (or cleared); the app restarts
 */
export const zSetAppLarkAppResponse = zLarkAppAck;

/**
 * Unbound; the console is open again
 */
export const zDeleteConsoleAuthResponse = zOkResponse;

/**
 * Console sign-in binding
 */
export const zGetConsoleAuthResponse = zConsoleAuthView;

export const zPutConsoleAuthBody = zBindReq;

/**
 * Binding saved; sign-in now required
 */
export const zPutConsoleAuthResponse = zOkResponse;

export const zStreamEventsQuery = z.object({
    since: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).register(z.globalRegistry, {
        description: 'Replay events with id greater than this (same role as `Last-Event-ID`).'
    }).optional()
});

/**
 * SSE stream of console events; each message's `data` is one JSON `Event`
 */
export const zStreamEventsResponse = zEvent;

/**
 * Service is up
 */
export const zHealthResponse = z.string().register(z.globalRegistry, {
    description: 'Service is up'
});

/**
 * Registered Lark apps (secrets redacted)
 */
export const zListLarkAppsResponse = zLarkAppsResponse;

export const zUpsertLarkAppBody = zUpsertReq;

/**
 * Credentials valid and saved
 */
export const zUpsertLarkAppResponse = zUpsertAck;

export const zTestLarkAppBody = zTestReq;

/**
 * Credential-test verdict
 */
export const zTestLarkAppResponse = zTestResult;

export const zDeleteLarkAppPath = z.object({
    name: z.string().register(z.globalRegistry, {
        description: 'Registry entry name'
    })
});

/**
 * Entry removed
 */
export const zDeleteLarkAppResponse = zOkResponse;

/**
 * Per-subsystem status snapshot
 */
export const zGetStatusResponse = zStatusResponse;

export const zCallbackQuery = z.object({
    code: z.string().register(z.globalRegistry, {
        description: 'Authorization code from Lark (present on success).'
    }).optional(),
    state: z.string().register(z.globalRegistry, {
        description: 'Opaque state echoed back; must match the login handshake.'
    }).optional(),
    error: z.string().register(z.globalRegistry, {
        description: 'Error code from Lark (present when the user denied access).'
    }).optional()
});

/**
 * Session cleared
 */
export const zLogoutResponse = z.void().register(z.globalRegistry, {
    description: 'Session cleared'
});

/**
 * Auth + current session state
 */
export const zMeResponse = zMe;
