import { defineConfig } from "@hey-api/openapi-ts";

// Input comes from the committed spec dump (`cargo xtask dump-openapi`), so
// codegen never needs a running console. OPENAPI_URL overrides it to generate
// against a live server instead.
export default defineConfig({
  input: {
    path: process.env.OPENAPI_URL || "./openapi.json",
  },
  output: {
    importFileExtension: undefined,
    header: [
      "// biome-ignore-all format: This file is auto-generated by @hey-api/openapi-ts",
      "// biome-ignore-all lint: This file is auto-generated by @hey-api/openapi-ts",
    ],
    path: "src/sdk",
  },
  plugins: [
    {
      name: "@hey-api/sdk",
      // Response validation only: request shapes are already enforced by
      // TypeScript, and Hey API's request validator is broken with Headers
      // (https://github.com/hey-api/hey-api/issues/2537).
      validator: { response: "zod" },
      operations: { strategy: "flat" },
      includeInEntry: true,
    },
    {
      name: "@hey-api/client-ky",
      // Hey API runs zod's throwing parseAsync either way, so make every
      // error a thrown error for consistency.
      throwOnError: true,
      includeInEntry: true,
    },
    {
      name: "zod",
      metadata: true,
      includeInEntry: true,
    },
    {
      name: "@hey-api/typescript",
      comments: true,
      enums: true,
      includeInEntry: true,
    },
  ],
});
